### ISSUE TITLE
Comparison with Llama3

### ISSUE THREAD

**Issue by elmoBG8** [McGill-NLP/webllama#6]
I see you compared your version with other models, but what about the version from which you derived it?
Thanks

**Comment by xhluca** [comment]
In the [weblinx paper](https://arxiv.org/abs/2402.05930), we have found that non-finetuned models are not as good as finetuned models, so it is unlikely that Llama-3-8b-Instruct surpasses Llama-3-8B-Web. However, if you think it's worth adding the results, it should be fairly straightforward to run the eval script with minor changes to the config: https://github.com/McGill-NLP/webllama/tree/main/modeling#run-llama-on-evaluation-splits
