### ISSUE TITLE
TypeError: snapshot_download() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given

### ISSUE THREAD

**Issue by icivi** [McGill-NLP/webllama#7]
----> 7 snapshot_download("McGill-NLP/WebLINX", "dataset", allow_patterns="templates/*")
      8 template = open('templates/llama.txt').read()
      9 

[/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py](https://localhost:8080/#) in _inner_fn(*args, **kwargs)
    117             kwargs = smoothly_deprecate_use_auth_token(fn_name=fn.__name__, has_token=has_token, kwargs=kwargs)
    118 
--> 119         return fn(*args, **kwargs)
    120 
    121     return _inner_fn  # type: ignore

TypeError: snapshot_download() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given

**Comment by xhluca** [comment]
#8 fixes the example
